### ISSUE TITLE
Grab the public ip if the hostname doesn't exist

### ISSUE THREAD

**Issue by douglasjarquin** [douglasjarquin/capistrano-ec2tag#2]
Some EC2 instances don't have public hostnames. Specifically, servers inside of a VPC. When a public hostname isn't found, use the public ip instead.

**Comment by cbake6807** [comment]
has this been implemented yet?

I, [2013-03-13T08:02:09.358939 #44662]  INFO -- : New RightAws::Ec2 using shared connections mode
I, [2013-03-13T08:02:09.359449 #44662]  INFO -- : Opening new HTTPS connection to ec2.amazonaws.com:443
/Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/server_definition.rb:16:in `initialize': undefined method`match' for nil:NilClass (NoMethodError)
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:57:in `new'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:57:in`block in role'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:57:in `each'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:57:in`role'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:69:in `block in server'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:69:in`each'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-2.14.1/lib/capistrano/configuration/roles.rb:69:in `server'
        from /Users/cbake6807/.rvm/gems/ruby-1.9.3-p194/gems/capistrano-ec2tag-0.0.3/lib/capistrano/ec2tag.rb:15:in`block in tag'

**Comment by douglasjarquin** [comment]
@cbake6807 Sorry for the late response, but yes. First, we check for public_hostname, but if it doesn't exist we pull the public_ipv4. Committed in https://github.com/douglasjarquin/capistrano-ec2tag/commit/e37271929b8b9f0ec3ca344c8d9dd28fe15d1936.
